import 'package:equatable/equatable.dart';import 'package:flutter/material.dart';import '/core/app_export.dart';import '../models/imageanddetails_item_model.dart';import '../models/images_item_model.dart';import '../models/cards_item_model.dart';import 'package:aswini_s_application5/presentation/product_details_screen/models/product_details_model.dart';part 'product_details_event.dart';part 'product_details_state.dart';/// A bloc that manages the state of a ProductDetails according to the event that is dispatched to it.
class ProductDetailsBloc extends Bloc<ProductDetailsEvent, ProductDetailsState> {ProductDetailsBloc(ProductDetailsState initialState) : super(initialState) { on<ProductDetailsInitialEvent>(_onInitialize); on<ChangeRadioButtonEvent>(_changeRadioButton); }

_changeRadioButton(ChangeRadioButtonEvent event, Emitter<ProductDetailsState> emit, ) { emit(state.copyWith(radioGroup: event.value)); } 
List<ImageanddetailsItemModel> fillImageanddetailsItemList() { return List.generate(1, (index) => ImageanddetailsItemModel()); } 
List<ImagesItemModel> fillImagesItemList() { return [ImagesItemModel(one: ImageConstant.img1)]; } 
List<CardsItemModel> fillCardsItemList() { return [CardsItemModel(image: ImageConstant.imgRectangle4224, theNewSchoolAt: "The New School At South Shore", publicPrekEight: "Public, Prek-8 - 583 students - 0.4 mi", reviewsCounter: "12 reviews"), CardsItemModel(image: ImageConstant.imgRectangle422462x62, theNewSchoolAt: "Wing Luke Elementary School", publicPrekEight: "Public, K-5 - 331 students - 0.4 mi", reviewsCounter: "0 reviews"), CardsItemModel(image: ImageConstant.imgRectangle42241, theNewSchoolAt: "Pathfinder K-8", publicPrekEight: "Public, K-8 - 488 students - 4.5 mi")]; } 
_onInitialize(ProductDetailsInitialEvent event, Emitter<ProductDetailsState> emit, ) async  { emit(state.copyWith(sliderIndex: 0, radioGroup: "")); emit(state.copyWith(productDetailsModelObj: state.productDetailsModelObj?.copyWith(imageanddetailsItemList: fillImageanddetailsItemList(), imagesItemList: fillImagesItemList(), cardsItemList: fillCardsItemList()))); } 
 }
