import 'package:equatable/equatable.dart';import 'package:flutter/material.dart';import '/core/app_export.dart';import '../models/propertytypechipview_item_model.dart';import '../models/optionschipview_item_model.dart';import 'package:aswini_s_application5/presentation/filter_page/models/filter_model.dart';part 'filter_event.dart';part 'filter_state.dart';/// A bloc that manages the state of a Filter according to the event that is dispatched to it.
class FilterBloc extends Bloc<FilterEvent, FilterState> {FilterBloc(FilterState initialState) : super(initialState) { on<FilterInitialEvent>(_onInitialize); on<ChangeDropDownEvent>(_changeDropDown); on<ChangeDropDown1Event>(_changeDropDown1); on<ChangeDropDown2Event>(_changeDropDown2); on<ChangeDropDown3Event>(_changeDropDown3); on<UpdateChipViewEvent>(_updateChipView); on<UpdateChipView1Event>(_updateChipView1); }

_onInitialize(FilterInitialEvent event, Emitter<FilterState> emit, ) async  { emit(state.copyWith(filterModelObj: state.filterModelObj?.copyWith(dropdownItemList: fillDropdownItemList(), dropdownItemList1: fillDropdownItemList1(), dropdownItemList2: fillDropdownItemList2(), dropdownItemList3: fillDropdownItemList3(), propertytypechipviewItemList: fillPropertytypechipviewItemList(), optionschipviewItemList: fillOptionschipviewItemList()))); } 
_changeDropDown(ChangeDropDownEvent event, Emitter<FilterState> emit, ) { emit(state.copyWith(selectedDropDownValue: event.value)); } 
_changeDropDown1(ChangeDropDown1Event event, Emitter<FilterState> emit, ) { emit(state.copyWith(selectedDropDownValue1: event.value)); } 
_changeDropDown2(ChangeDropDown2Event event, Emitter<FilterState> emit, ) { emit(state.copyWith(selectedDropDownValue2: event.value)); } 
_changeDropDown3(ChangeDropDown3Event event, Emitter<FilterState> emit, ) { emit(state.copyWith(selectedDropDownValue3: event.value)); } 
_updateChipView(UpdateChipViewEvent event, Emitter<FilterState> emit, ) { List<PropertytypechipviewItemModel> newList = List<PropertytypechipviewItemModel>.from(state.filterModelObj!.propertytypechipviewItemList); newList[event.index] = newList[event.index].copyWith(isSelected: event.isSelected); emit(state.copyWith(filterModelObj: state.filterModelObj?.copyWith(propertytypechipviewItemList: newList))); } 
_updateChipView1(UpdateChipView1Event event, Emitter<FilterState> emit, ) { List<OptionschipviewItemModel> newList = List<OptionschipviewItemModel>.from(state.filterModelObj!.optionschipviewItemList); newList[event.index] = newList[event.index].copyWith(isSelected: event.isSelected); emit(state.copyWith(filterModelObj: state.filterModelObj?.copyWith(optionschipviewItemList: newList))); } 
List<SelectionPopupModel> fillDropdownItemList() { return [SelectionPopupModel(id: 1, title: "Item One", isSelected: true), SelectionPopupModel(id: 2, title: "Item Two"), SelectionPopupModel(id: 3, title: "Item Three")]; } 
List<SelectionPopupModel> fillDropdownItemList1() { return [SelectionPopupModel(id: 1, title: "Item One", isSelected: true), SelectionPopupModel(id: 2, title: "Item Two"), SelectionPopupModel(id: 3, title: "Item Three")]; } 
List<SelectionPopupModel> fillDropdownItemList2() { return [SelectionPopupModel(id: 1, title: "Item One", isSelected: true), SelectionPopupModel(id: 2, title: "Item Two"), SelectionPopupModel(id: 3, title: "Item Three")]; } 
List<SelectionPopupModel> fillDropdownItemList3() { return [SelectionPopupModel(id: 1, title: "Item One", isSelected: true), SelectionPopupModel(id: 2, title: "Item Two"), SelectionPopupModel(id: 3, title: "Item Three")]; } 
List<PropertytypechipviewItemModel> fillPropertytypechipviewItemList() { return List.generate(5, (index) => PropertytypechipviewItemModel()); } 
List<OptionschipviewItemModel> fillOptionschipviewItemList() { return List.generate(8, (index) => OptionschipviewItemModel()); } 
 }
